mod:LShift,mod:LCtrl,mod:LAlt,mod:RShift,mod:RCtrl,mod:RAlt
mod:LShift,mod:LCtrl,mod:LAlt,mod:RShift,mod:RCtrl,nomod:RAlt
mod:LShift,mod:LCtrl,mod:LAlt,mod:RShift,mod:RAlt,nomod:RCtrl
mod:LShift,mod:LCtrl,mod:LAlt,mod:RShift,nomod:RCtrl,nomod:RAlt
mod:LShift,mod:LCtrl,mod:LAlt,mod:RCtrl,mod:RAlt,nomod:RShift
mod:LShift,mod:LCtrl,mod:LAlt,mod:RCtrl,nomod:RShift,nomod:RAlt
mod:LShift,mod:LCtrl,mod:LAlt,mod:RAlt,nomod:RShift,nomod:RCtrl
mod:LShift,mod:LCtrl,mod:LAlt,nomod:RShift,nomod:RCtrl,nomod:RAlt
mod:LShift,mod:LCtrl,mod:RShift,mod:RCtrl,mod:RAlt,nomod:LAlt
mod:LShift,mod:LCtrl,mod:RShift,mod:RCtrl,nomod:LAlt,nomod:RAlt
mod:LShift,mod:LCtrl,mod:RShift,mod:RAlt,nomod:LAlt,nomod:RCtrl
mod:LShift,mod:LCtrl,mod:RShift,nomod:LAlt,nomod:RCtrl,nomod:RAlt
mod:LShift,mod:LCtrl,mod:RCtrl,mod:RAlt,nomod:LAlt,nomod:RShift
mod:LShift,mod:LCtrl,mod:RCtrl,nomod:LAlt,nomod:RShift,nomod:RAlt
mod:LShift,mod:LCtrl,mod:RAlt,nomod:LAlt,nomod:RShift,nomod:RCtrl
mod:LShift,mod:LCtrl,nomod:LAlt,nomod:RShift,nomod:RCtrl,nomod:RAlt
mod:LShift,mod:LAlt,mod:RShift,mod:RCtrl,mod:RAlt,nomod:LCtrl
mod:LShift,mod:LAlt,mod:RShift,mod:RCtrl,nomod:LCtrl,nomod:RAlt
mod:LShift,mod:LAlt,mod:RShift,mod:RAlt,nomod:LCtrl,nomod:RCtrl
mod:LShift,mod:LAlt,mod:RShift,nomod:LCtrl,nomod:RCtrl,nomod:RAlt
mod:LShift,mod:LAlt,mod:RCtrl,mod:RAlt,nomod:LCtrl,nomod:RShift
mod:LShift,mod:LAlt,mod:RCtrl,nomod:LCtrl,nomod:RShift,nomod:RAlt
mod:LShift,mod:LAlt,mod:RAlt,nomod:LCtrl,nomod:RShift,nomod:RCtrl
mod:LShift,mod:LAlt,nomod:LCtrl,nomod:RShift,nomod:RCtrl,nomod:RAlt
mod:LShift,mod:RShift,mod:RCtrl,mod:RAlt,nomod:LCtrl,nomod:LAlt
mod:LShift,mod:RShift,mod:RCtrl,nomod:LCtrl,nomod:LAlt,nomod:RAlt
mod:LShift,mod:RShift,mod:RAlt,nomod:LCtrl,nomod:LAlt,nomod:RCtrl
mod:LShift,mod:RShift,nomod:LCtrl,nomod:LAlt,nomod:RCtrl,nomod:RAlt
mod:LShift,mod:RCtrl,mod:RAlt,nomod:LCtrl,nomod:LAlt,nomod:RShift
mod:LShift,mod:RCtrl,nomod:LCtrl,nomod:LAlt,nomod:RShift,nomod:RAlt
mod:LShift,mod:RAlt,nomod:LCtrl,nomod:LAlt,nomod:RShift,nomod:RCtrl
mod:LShift,nomod:LCtrl,nomod:LAlt,nomod:RShift,nomod:RCtrl,nomod:RAlt
mod:LCtrl,mod:LAlt,mod:RShift,mod:RCtrl,mod:RAlt,nomod:LShift
mod:LCtrl,mod:LAlt,mod:RShift,mod:RCtrl,nomod:LShift,nomod:RAlt
mod:LCtrl,mod:LAlt,mod:RShift,mod:RAlt,nomod:LShift,nomod:RCtrl
mod:LCtrl,mod:LAlt,mod:RShift,nomod:LShift,nomod:RCtrl,nomod:RAlt
mod:LCtrl,mod:LAlt,mod:RCtrl,mod:RAlt,nomod:LShift,nomod:RShift
mod:LCtrl,mod:LAlt,mod:RCtrl,nomod:LShift,nomod:RShift,nomod:RAlt
mod:LCtrl,mod:LAlt,mod:RAlt,nomod:LShift,nomod:RShift,nomod:RCtrl
mod:LCtrl,mod:LAlt,nomod:LShift,nomod:RShift,nomod:RCtrl,nomod:RAlt
mod:LCtrl,mod:RShift,mod:RCtrl,mod:RAlt,nomod:LShift,nomod:LAlt
mod:LCtrl,mod:RShift,mod:RCtrl,nomod:LShift,nomod:LAlt,nomod:RAlt
mod:LCtrl,mod:RShift,mod:RAlt,nomod:LShift,nomod:LAlt,nomod:RCtrl
mod:LCtrl,mod:RShift,nomod:LShift,nomod:LAlt,nomod:RCtrl,nomod:RAlt
mod:LCtrl,mod:RCtrl,mod:RAlt,nomod:LShift,nomod:LAlt,nomod:RShift
mod:LCtrl,mod:RCtrl,nomod:LShift,nomod:LAlt,nomod:RShift,nomod:RAlt
mod:LCtrl,mod:RAlt,nomod:LShift,nomod:LAlt,nomod:RShift,nomod:RCtrl
mod:LCtrl,nomod:LShift,nomod:LAlt,nomod:RShift,nomod:RCtrl,nomod:RAlt
mod:LAlt,mod:RShift,mod:RCtrl,mod:RAlt,nomod:LShift,nomod:LCtrl
mod:LAlt,mod:RShift,mod:RCtrl,nomod:LShift,nomod:LCtrl,nomod:RAlt
mod:LAlt,mod:RShift,mod:RAlt,nomod:LShift,nomod:LCtrl,nomod:RCtrl
mod:LAlt,mod:RShift,nomod:LShift,nomod:LCtrl,nomod:RCtrl,nomod:RAlt
mod:LAlt,mod:RCtrl,mod:RAlt,nomod:LShift,nomod:LCtrl,nomod:RShift
mod:LAlt,mod:RCtrl,nomod:LShift,nomod:LCtrl,nomod:RShift,nomod:RAlt
mod:LAlt,mod:RAlt,nomod:LShift,nomod:LCtrl,nomod:RShift,nomod:RCtrl
mod:LAlt,nomod:LShift,nomod:LCtrl,nomod:RShift,nomod:RCtrl,nomod:RAlt
mod:RShift,mod:RCtrl,mod:RAlt,nomod:LShift,nomod:LCtrl,nomod:LAlt
mod:RShift,mod:RCtrl,nomod:LShift,nomod:LCtrl,nomod:LAlt,nomod:RAlt
mod:RShift,mod:RAlt,nomod:LShift,nomod:LCtrl,nomod:LAlt,nomod:RCtrl
mod:RShift,nomod:LShift,nomod:LCtrl,nomod:LAlt,nomod:RCtrl,nomod:RAlt
mod:RCtrl,mod:RAlt,nomod:LShift,nomod:LCtrl,nomod:LAlt,nomod:RShift
mod:RCtrl,nomod:LShift,nomod:LCtrl,nomod:LAlt,nomod:RShift,nomod:RAlt
mod:RAlt,nomod:LShift,nomod:LCtrl,nomod:LAlt,nomod:RShift,nomod:RCtrl
